server:
  port: 9091

spring:
  #测试环境
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.2.153:1521/aeods
    username: SSDT_AGILE_PROJECT_COPY1
    password: SSDT_AGILE_PROJECT_COPY1
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB

  ##AD认证
  ldap:
    ##AD服务器IP，默认端口389
    urls: ldap://10.250.20.1:389
    ##登录账号
    username: ssdt_bpm
    ##密码
    password: p@ssw0rd001
    #distinguishedName的部分节点
    base: DC=SSDTC,DC=com

    ## Redis连接
  redis:
    host: 192.168.2.172
    port: 6379
    password: Touchspring1
    database: 0
    lettuce:
      pool:
        max-idle: 8
        max-active: 16
        min-idle: 0
        max-wait: -1ms
    timeout: 9999ms

  ## 王静----邮箱测试
  mail:
    host: smtp.163.com #发送邮件服务器
    username: 18862671539@163.com #发送邮件的邮箱地址
    password:  LQRRCEOLUXZDDWZI #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 994 #465或者994
    from: 18862671539@163.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

## 邮件中，访问的路径前缀
path:
  prefix: @path.prefix@

##配置 已删除/未删除的状态码
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      # 1 代表已删除，不配置默认是1，也可修改配置
      logic-delete-value: 1
      # 0 代表未删除，不配置默认是0，也可修改配置
      logic-not-delete-value: 0

logging:
  pattern:
    console: "%d - %msg%n"
  level:
    com.touchspring.ailge: info
    com.baomidou.example.mapper: info
    org.springframework.web: info
  file:
    path: @system.filePath@/log

system:
  filePath: @system.filePath@

login:
  type: search_sql

jodconverter:
  local:
    enabled: true
    ##本地服务地址
#    office-home: C:\Program Files (x86)\OpenOffice 4
    ##服务器服务地址
    office-home: /opt/openoffice4
    max-tasks-per-process: 10
    port-numbers: 8100
